version: '3.7'

services:
  instagram_db:
    container_name: instagram_db
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=root1
      - POSTGRES_USER=admin1
    image: postgres:15.3-alpine
